name: Continuous Delivery

on:
  pull_request:
    branches:
      - main  

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v5

            -   name: Login to Docker Hub
                uses: docker/login-action@v3

                with:
                    username: ${{ vars.DOCKER_USER }}
                    password: ${{ secrets.DOCKER_TOKEN }}
                    
            -   name: Build da imagem Docker 
                run: docker build -t rafaooo/testecp:latest .

            -   name: Push da imagem Docker para o Docker Hub    
                run: docker push rafaooo/testecp:latest
              